### ISSUE TITLE
Remove TAGFILES from doc/Doxygen.extra.in

### ISSUE THREAD

**Issue by nim65s** [humanoid-path-planner/hpp-gepetto-viewer#23]
https://github.com/humanoid-path-planner/hpp-gepetto-viewer/blob/629e0279355ca03bdde763a549252bd627d7964b/doc/Doxyfile.extra.in#L1

According to robotpkg's patch-aa,
> Disable tagfiles, this triggers a segfault in doxygen-1.8.6 while processing
> the gepetto-viewer-corba.doxytag
> This does not change the documentation anyway: the generated "related pages" is
> empty even with tagfiles on.

**Comment by jmirabel** [comment]
Yes, we know. The bug is corrected from Doxygen 1.8.10. It fails on Ubuntu 14.04 and succeed on Ubuntu 16.04.

**Comment by jmirabel** [comment]
>>This does not change the documentation anyway: the generated "related pages" is
empty even with tagfiles on.

Not true: it removes the links to classes that are in other packages and results from the search bar will not include other packages.

**Comment by jmirabel** [comment]
Moreover, recent versions of cmake submodule automatically fills `TAGFILES` variables. If you want to disable it in robotpkg (for 14.04 only, please) then you have to set it to an empty value rather than just removing it.

**Comment by jmirabel** [comment]
I close this. @nim65s re-open if necessary.
