### ISSUE TITLE
Viewer client does not work anymore in manipulation

### ISSUE THREAD

**Issue by florent-lamiraux** [humanoid-path-planner/hpp-gepetto-viewer#37]
Method createViewer of manipulation.ViewerFactory fails because of keyword `ghost`. I will propose a fix.
However, the following line does not work in manipulation since `self.problemSolver.client.problem` should be replaced by `self.problemSolver.client.manipulation.problem`. I do not know whether there is a way to write it that would be valid in manipulation and in general case. @jmirabel : what do you think?
https://github.com/humanoid-path-planner/hpp-gepetto-viewer/blob/1222edaf8654cdf14c652a127c5e7d3f957926ea/src/hpp/gepetto/viewer.py#L139

**Comment by jmirabel** [comment]
I forgot about this two points.
The first should be easy to fix by looking at hpp.gepetto.ViewerFactory.createViewer.

For the second, the line you mention should be replaced by
```python
 self.amax = omniORB.any.from_any(self.problemSolver.hppcorba.problem.getParameter("Kinodynamic/accelerationBound")) 
```

**Comment by florent-lamiraux** [comment]
Thank you. I made a pull request that should fix the issue. @pFernbach can you test that it still work for you ?

**Comment by pFernbach** [comment]
Yes it work for me. But actually I introduced an indentation error in my previous pull request. The two lines that set `amax` and `vmax` should be inside the `if displayArrows :`.

Sorry about that, can you fix it in your open PR ?

**Comment by florent-lamiraux** [comment]
I made the requested modification. Once you confirm that it is all right, I merge.

**Comment by pFernbach** [comment]
I confirm, thanks.

**Comment by florent-lamiraux** [comment]
Solved by https://github.com/humanoid-path-planner/hpp-gepetto-viewer/pull/38.
