### ISSUE TITLE
Corbaserver/Gepetto is unable to read .dae files

### ISSUE THREAD

**Issue by GauDelpech** [humanoid-path-planner/hpp-gepetto-viewer#44]
Hi hpp team,

After reinstalling hhp on my computer a python script that I've made (that used to work well) doesn't work anymore due to a fail in reading .dae files when I try to load a robot.
Here is the issue that I have : 
```
Traceback (most recent call last):
  File "perso.py", line 52, in <module>
    v = vf.createViewer()
  File "/home/dem/Documents/hpp/install/lib/python2.7/dist-packages/hpp/gepetto/viewer_factory.py", line 120, in createViewer
    v = ViewerClass (self.problemSolver, viewerClient, ghost = ghost, *args, **kwargs)
  File "/home/dem/Documents/hpp/install/lib/python2.7/dist-packages/hpp/gepetto/viewer.py", line 121, in __init__
    self._initDisplay ()
  File "/home/dem/Documents/hpp/install/lib/python2.7/dist-packages/hpp/gepetto/viewer.py", line 165, in _initDisplay
    self.client.gui.addURDF (self.displayName, urdfFilename)
  File "/home/dem/Documents/hpp/install/lib/python2.7/dist-packages/gepetto/corbaserver/graphical_interface_idl.py", line 450, in addURDF
    return self._obj.invoke("addURDF", _0_gepetto.corbaserver.GraphicalInterface._d_addURDF, args)
gepetto.corbaserver.gepetto.Error: gepetto.corbaserver.gepetto.Error(msg='File /home/dem/Documents/hpp/install/share/example-robot-data/robots/ur_description/meshes/ur5/visual/base.dae found but could not be opened. Check that a plugin exist.')
```
Apparently a plugin is missing but I can't find what one.
Have you any idea of a plugin that I should use to solve my problem ?

Thanks for your help,
Gauthier

**Comment by florent-lamiraux** [comment]
You probrably miss binary package `robotpkg-qt5-osgqt` (or `robotpkg-qt4-osgqt` depending on the qt version you compile HPP against). You can see qt version in the Makefile.

**Comment by jmirabel** [comment]
How did you install gepetto viewer ?

**Comment by GauDelpech** [comment]
Hello, I used the source installation of HPP stable version for Ubuntu 18.04

**Comment by jmirabel** [comment]
Can you retry after having run `sudo apt install robotpkg-osg-dae` ?

**Comment by GauDelpech** [comment]
I've downloaded `robotpkg-qt4-osgqt` but the same error still occur. 
And when I try  `sudo apt install robotpkg-osg-dae` I receive an error : 
```
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
E: Impossible de trouver le paquet robotpkg-osg-dae
```

**Comment by jmirabel** [comment]
Then, the best solution is to remove `libopenscenegraph*` and install `robotpkg-openscenegraph`.

**Comment by jmirabel** [comment]
For HPP developers : GV is now stable enough. It would probably be easier to make it a binary dependency rather than a source dependency.

**Comment by GauDelpech** [comment]
Thanks,
I think I got rid of my problem by removing  `libopenscenegraph*` and redoing the source installation.
