### ISSUE TITLE
Robotpkg error

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/hpp-gepetto-viewer#69]
Hi,

I get the following error when building the package with robotpkg:
```
CMake Error at src/CMakeLists.txt:23 (python_install_on_site):
Unknown CMake command "python_install_on_site".
Call Stack (most recent call first):
src/CMakeLists.txt:28 (install_python_files)


-- Configuring incomplete, errors occurred!
```

I'm a little surprised since this has not changed and it seems the CMake submodule has no changes related to this. Anyone understands the issue ?

EDIT: I still don't understand why it passed on robotpkg build farm: http://robotpkg.openrobots.org/rbulk/robotpkg/graphics/py-qt-hpp-gepetto-viewer/index.html#py38-qt5-hpp-gepetto-viewer-4.15.1

**Comment by jmirabel** [comment]
Just found the culprit: https://github.com/humanoid-path-planner/hpp-gepetto-viewer/commit/5e8bf2167a7401e9cf2b9e34a8b14f34fe3c7204 removed the inclusion of `cmake/python.cmake`.

@nim65s shouldn't we revert this change ?

**Comment by nim65s** [comment]
Reverting alone would break something else.
This was fixed by a fence in other packages, but it looks like I missed this one, I'll add it back
